# Generated by Django 3.2.5 on 2021-07-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotekaApp', '0002_alter_ksiazka_uzytkownik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='typ_okladki',
            field=models.CharField(choices=[('twarda', 'twarda'), ('', 'miekka')], default='', max_length=32),
        ),
    ]
