# Generated by Django 3.2.5 on 2021-07-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotekaApp', '0004_auto_20210721_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='data_publikacji',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
