# Generated by Django 3.2.5 on 2021-07-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotekaApp', '0005_alter_ksiazka_data_publikacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='typ_okladki',
            field=models.CharField(choices=[('miekka', 'miekka'), ('twarda', 'twarda')], default='miekka', max_length=32),
        ),
    ]
