# Generated by Django 3.2.5 on 2021-07-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotekaApp', '0003_alter_ksiazka_typ_okladki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='data_premiery',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='typ_okladki',
            field=models.CharField(choices=[('twarda', 'twarda'), ('miekka', 'miekka')], default='miekka', max_length=32),
        ),
    ]
