# Generated by Django 3.2.5 on 2021-07-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BibliotekaApp', '0006_auto_20210725_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='is_active',
            field=models.IntegerField(default=1),
        ),
    ]
